name: pref_look
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch==0.4.1
  - cudatoolkit=11.0
  - torchvision
  - python=3.6.5
  - pip:
    - dlib==19.23.1
    - imutils==0.5.4
    - opencv-python==4.5.5.64
    - scikit-learn==0.24.2
    - scipy==1.5.4
